### ISSUE TITLE
Comment counter hidden on mobile, portrait mode

### ISSUE THREAD

**Issue by mtchllbrrn** [goddamnyouryan/coven#15]
See title. In addition, the text sometimes gets cut off for longer titles in landscape mode. 

Should be a simple css fix. I can take a look and submit a PR, if you like. 

iPhone 6, Safari

**Comment by goddamnyouryan** [comment]
@mtchllbrrn If you could take a look that would be much appreciated. I'll approve a PR no problem

**Comment by goddamnyouryan** [comment]
Merged! Pushing to live currently.
