### ISSUE TITLE
Rails Application Error

### ISSUE THREAD

**Issue by colinrobertbrooks** [goddamnyouryan/coven#21]
http://api.coven.link/api/v1/posts?sources=HackerNews%2CProductHunt%2CRProgramming%2CBarnacles
![image](https://user-images.githubusercontent.com/9815009/142643742-78574bb9-7161-498f-a599-08f01e9c6805.png)

**Comment by goddamnyouryan** [comment]
Hi! Sorry for the delay. I think this is just from the https://github.com/goddamnyouryan/coven-api being very old. I think if you could get the Ruby gems / verison of Ruby updated it should fix the problem but unfortunately I don't have time to work on this project anymore.

**Comment by goddamnyouryan** [comment]
Ok I changed my mind and just fixed it. Should be working again.
