### ISSUE TITLE
Error on all feeds

### ISSUE THREAD

**Issue by siathalysedI** [goddamnyouryan/coven#22]
I got this message on all feeds

```
GET http://api.coven.link/api/v1/posts?sources=HackerNews%2CLobsters%2CProductHunt%2CRProgramming%2CBarnacles net::ERR_FAILED 503
```

And in this service I got 
```
Application Error
````
```
http://api.coven.link/api/v1/posts
```

All of them from www.coven.link

Any help is welcome.

Thanks

**Comment by goddamnyouryan** [comment]
Hi! Sorry for the delay. I think this is just from the https://github.com/goddamnyouryan/coven-api being very old. I think if you could get the Ruby gems / verison of Ruby updated it should fix the problem but unfortunately I don't have time to work on this project anymore.

**Comment by goddamnyouryan** [comment]
Ok I changed my mind, I actually fixed this issue. Should be working again.
